# Generated by Django 5.0.7 on 2024-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=10)),
                ('exchange_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
    ]
