services:
  django:
    container_name: django
    build:
      context: ./stockwatcher
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stockwatcher:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-f&qv6038$(%v4&426s=q-@f^(xkw2a&(l%4(kia(kbm0#2^)en
      - ALLOWED_HOSTS=localhost,127.0.0.1
