services:
    postgres:
        image: postgres
        container_name: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - .env

    redis:
        container_name: redis
        image: redis
        restart: always
        entrypoint: redis-server --port ${REDIS_PORT} --appendonly yes
        depends_on:
            postgres:
                condition: service_started

    django:
        container_name: django
        build:
            context: .
        entrypoint: /usr/src/entrypoint.sh
        volumes:
            - ./src:/usr/src/app
        ports:
            - 8001:8000
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_started

    celery:
        container_name: celery
        build:
            context: .
        entrypoint: /usr/src/celery_entrypoint.sh
        volumes:
            - ./src:/usr/src/app
        env_file:
            - .env
        restart: on-failure
        depends_on:
            django:
                condition: service_started
