services:
    postgres:
        image: postgres
        container_name: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - .env

    redis:
        container_name: redis
        image: redis
        restart: always
        entrypoint: redis-server --port ${REDIS_PORT} --appendonly yes
        depends_on:
            - postgres

    django:
        container_name: django
        build:
            context: .
        entrypoint: /usr/src/entrypoint.sh
        volumes:
            - ./src:/usr/src/app
        ports:
            - 8001:8000
        env_file:
            - .env
        depends_on:
            - postgres
            - redis

    celery:
        container_name: celery
        build:
            context: .
        command: celery -A stockwatcher worker --beat -l INFO
        volumes:
            - ./src:/usr/src/app
        env_file:
            - .env
        depends_on:
            - django
