# Generated by Django 5.0.7 on 2024-07-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='watch',
            field=models.BooleanField(default=True, help_text='Scrape price every minute?'),
        ),
    ]
