# Generated by Django 5.0.7 on 2024-07-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_watch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('ticker',), 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'verbose_name_plural': 'Stock Prices'},
        ),
    ]
