# Generated by Django 5.0.7 on 2024-07-26 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock'),
        ),
        migrations.CreateModel(
            name='UserStockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time_interval', models.IntegerField(default=1)),
                ('tunnel_time_interval', models.IntegerField(default=0)),
                ('tunnel_range', models.FloatField(default=0.1)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_configs', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
