# Generated by Django 5.0.7 on 2024-07-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stock_last_closing_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('ticker',), 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ('timestamp',), 'verbose_name': 'Stock Price', 'verbose_name_plural': 'Stock Prices'},
        ),
        migrations.AlterModelOptions(
            name='userstockconfig',
            options={'verbose_name': 'User Stock Config', 'verbose_name_plural': 'User Stock Stock Configs'},
        ),
    ]
